# Generated by Django 5.1 on 2024-08-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_targetdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
